### ISSUE TITLE
using try-except block

### ISSUE THREAD

**Issue by am-thyst** [rainwoodman/sharedmem#14]
I'm trying to put a try-except block into my multiprocessing loop because there is one function (`surface_based_cape_cin`) which throws an error on certain grid-points. This is due to a bug that will be fixed in the next release, but I need to get as much as I can done asap. 

I've tried putting the try/except block in the following positions:

```python
with sharedmem.MapReduce(np=59) as pool:
  def cape_func(abc):
#### Tried it here
    for j in range((abc), abc+1):
      for k in range(241):  
        for l in range(480): # Europe
          pressure = [sfc_p[j,k,l], dict["p950"][j,k,l], dict["p900"][j,k,l], dict["p850"][j,k,l], dict["p800"][j,k,l], dict["p750"][j,k,l], dict["p700"][j,k,l], dict["p650"][j,k,l]] * units.hPa
          temperature = [sfc_t[j,k,l], dict["t950"][j,k,l], dict["t900"][j,k,l], dict["t850"][j,k,l], dict["t800"][j,k,l], dict["t750"][j,k,l], dict["t700"][j,k,l], dict["t650"][j,k,l]] * units.kelvin
          dewpoint = [sfc_dp[j,k,l], dict["dp950"][j,k,l], dict["dp900"][j,k,l], dict["dp850"][j,k,l], dict["dp800"][j,k,l], dict["dp750"][j,k,l], dict["dp700"][j,k,l], dict["dp650"][j,k,l]] * units.kelvin
#### Tried it here
          cape, cin = surface_based_cape_cin(pressure, temperature, dewpoint)
          cape = cape / (units.joule / units.kilogram)
          counter[j,k,l] = float(cape)
#### Tried it here
  pool.map(cape_func, range(0, int(datetime_range)-1))
```

But each time, I still get the traceback from the error. What am I doing wrong?

**Comment by rainwoodman** [comment]
How does the try except block look like?

Also, if you set np=0, `MapReduce` will run from the master thread (it actually just calls itertools.map). I would suggest you see if the error is also raised in that mode -- in that case it could be you may have a different exception handler inside your `surface_based_cape_cin function` that prints it and swallows it, and your try catch block never caught the exception.

**Comment by am-thyst** [comment]
@rainwoodman I tried setting the np=0, and still got the error 

here's an example of my block:

```python
with sharedmem.MapReduce(np=0) as pool:
  def cape_func(abc):
    for j in range((abc), abc+1):
      for k in range(241):  
        for l in range(480): # Europe
          pressure = [sfc_p[j,k,l], dict["p950"][j,k,l], dict["p900"][j,k,l], dict["p850"][j,k,l], dict["p800"][j,k,l], dict["p750"][j,k,l], dict["p700"][j,k,l], dict["p650"][j,k,l]] * units.hPa
          temperature = [sfc_t[j,k,l], dict["t950"][j,k,l], dict["t900"][j,k,l], dict["t850"][j,k,l], dict["t800"][j,k,l], dict["t750"][j,k,l], dict["t700"][j,k,l], dict["t650"][j,k,l]] * units.kelvin
          dewpoint = [sfc_dp[j,k,l], dict["dp950"][j,k,l], dict["dp900"][j,k,l], dict["dp850"][j,k,l], dict["dp800"][j,k,l], dict["dp750"][j,k,l], dict["dp700"][j,k,l], dict["dp650"][j,k,l]] * units.kelvin
          cape, cin = surface_based_cape_cin(pressure, temperature, dewpoint)
          cape = cape / (units.joule / units.kilogram)
          counter[j,k,l] = float(cape)
  try:
    pool.map(cape_func, range(0, int(datetime_range)-1))
  except sharedmem.sharedmem.StopProcessGroup or IndexError:
    print("abc =" + str(abc), "k =" + str(k), "l =" + str(l))
    sys.flush()
```

and the traceback:
```python
Traceback (most recent call last):
  File "/var/spool/torque/mom_priv/jobs/238790.rdf-xcat.SC", line 58, in <module>
    pool.map(cape_func, range(0, int(datetime_range)-1))
  File "/nerc/n02/n02/amethyst/minic/envs/newenv/lib/python3.7/site-packages/sharedmem/sharedmem.py", line 710, in map
    rt = [realreduce(realfunc(i)) for i in sequence]
  File "/nerc/n02/n02/amethyst/minic/envs/newenv/lib/python3.7/site-packages/sharedmem/sharedmem.py", line 710, in <listcomp>
    rt = [realreduce(realfunc(i)) for i in sequence]
  File "/nerc/n02/n02/amethyst/minic/envs/newenv/lib/python3.7/site-packages/sharedmem/sharedmem.py", line 703, in realfunc
    else: return func(i)
  File "/var/spool/torque/mom_priv/jobs/238790.rdf-xcat.SC", line 54, in cape_func
    cape, cin = surface_based_cape_cin(pressure, temperature, dewpoint)
  File "/nerc/n02/n02/amethyst/minic/envs/newenv/lib/python3.7/site-packages/metpy/xarray.py", line 436, in wrapper
    return func(*args, **kwargs)
  File "/nerc/n02/n02/amethyst/minic/envs/newenv/lib/python3.7/site-packages/metpy/units.py", line 305, in wrapper
    return func(*args, **kwargs)
  File "/nerc/n02/n02/amethyst/minic/envs/newenv/lib/python3.7/site-packages/metpy/calc/thermo.py", line 1697, in surface_based_cape_cin
    return cape_cin(p, t, td, profile)
  File "/nerc/n02/n02/amethyst/minic/envs/newenv/lib/python3.7/site-packages/metpy/xarray.py", line 436, in wrapper
    return func(*args, **kwargs)
  File "/nerc/n02/n02/amethyst/minic/envs/newenv/lib/python3.7/site-packages/metpy/units.py", line 305, in wrapper
    return func(*args, **kwargs)
  File "/nerc/n02/n02/amethyst/minic/envs/newenv/lib/python3.7/site-packages/metpy/calc/thermo.py", line 1374, in cape_cin
    parcel_temperature_profile=parcel_profile)
  File "/nerc/n02/n02/amethyst/minic/envs/newenv/lib/python3.7/site-packages/metpy/xarray.py", line 436, in wrapper
    return func(*args, **kwargs)
  File "/nerc/n02/n02/amethyst/minic/envs/newenv/lib/python3.7/site-packages/metpy/units.py", line 305, in wrapper
    return func(*args, **kwargs)
  File "/nerc/n02/n02/amethyst/minic/envs/newenv/lib/python3.7/site-packages/metpy/calc/thermo.py", line 424, in lfc
    return x[0], y[0]
  File "/nerc/n02/n02/amethyst/minic/envs/newenv/lib/python3.7/site-packages/pint/quantity.py", line 1281, in __getitem__
    value = self._magnitude[key]
IndexError: index 0 is out of bounds for axis 0 with size 0
```

What do you recommend as my next move?

**Comment by rainwoodman** [comment]
You sure 'or' is the syntax to catch multiple exceptions? I didnt know
this..

**Comment by emef** [comment]
should be 

```
try:
    pool.map(cape_func, range(0, int(datetime_range)-1))
  except (sharedmem.sharedmem.StopProcessGroup, IndexError):
    print("abc =" + str(abc), "k =" + str(k), "l =" + str(l))
    sys.flush()
```

I'm surprised it doesn't give you a syntax error for using `or` in the `except` block.

**Comment by am-thyst** [comment]
@rainwoodman @emef thanks guys! I'm a bit of a noob. I'll try it now :)

**Comment by syrte** [comment]
> should be
> 
> ```
> try:
>     pool.map(cape_func, range(0, int(datetime_range)-1))
>   except (sharedmem.sharedmem.StopProcessGroup, IndexError):
>     print("abc =" + str(abc), "k =" + str(k), "l =" + str(l))
>     sys.flush()
> ```
> I'm surprised it doesn't give you a syntax error for using `or` in the `except` block.

It's not a syntax error, becasue
```python
>>> sharedmem.sharedmem.StopProcessGroup or IndexError
sharedmem.sharedmem.StopProcessGroup
```
So acutally, the `IndexError` is ignored by short circuit of `or` operation 
```python
>>> bool(sharedmem.sharedmem.StopProcessGroup)
True
```

**Comment by rainwoodman** [comment]
I learned something new here -- thanks @syrte for the explanation!

**Comment by am-thyst** [comment]
@rainwoodman @syrte @emef thanks everyone for your help! I've managed to run my code, and only 8.68e-4% of my gridpoints didn't compute. Turns out I was just using the try-except block wrong (_next time read the documentation_)
