### ISSUE TITLE
AttributeError: Can't pickle local object 'MapReduce.map.<locals>.realfunc'

### ISSUE THREAD

**Issue by mortalcat** [rainwoodman/sharedmem#18]
Hi, I was trying to run your example on win32 with python 3.7.3, instead I've got this error message claiming that pickling is failed. Do you have any idea what is wrong?
Traceback (most recent call last):
  File "C:/Users/Shaocong/PycharmProjects/multiprocess/test.py", line 33, in <module>
    r = pool.map(work, range(0, len(xdx), chunksize), reduce=reduce)
  File "C:\Users\Shaocong\AppData\Local\Programs\Python\Python37\lib\site-packages\sharedmem\sharedmem.py", line 740, in map
    pg.start()
  File "C:\Users\Shaocong\AppData\Local\Programs\Python\Python37\lib\site-packages\sharedmem\sharedmem.py", line 390, in start
    x.start()
  File "C:\Users\Shaocong\AppData\Local\Programs\Python\Python37\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Users\Shaocong\AppData\Local\Programs\Python\Python37\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\Shaocong\AppData\Local\Programs\Python\Python37\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\Shaocong\AppData\Local\Programs\Python\Python37\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\Shaocong\AppData\Local\Programs\Python\Python37\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'MapReduce.map.<locals>.realfunc'

**Comment by rainwoodman** [comment]
sharedmem only works with fork. Win32s does not have a fork system call.

fork is provided by WSL, which provides the posix layer on the NT kernel:

https://docs.microsoft.com/en-us/windows/wsl/install-win10
